#pragma once

enum class EventMessage
{
	BEGIN_WIND,			//風の吹き始め
	STRONG_WIND,		//強い風が吹く
	ATTENUATE_WIND,		//風の威力の減衰
	END_WIND,			//風が終了
	START_LANE_CHANGE,
	END_LANE_CHANGE,
	GOAL_FLAG,			//ゴールフラグ
	GAME_CLEAR_FLAG,	//ステージ終了フラグ
	TAPPER_DEAD,	//叩き死亡
	PLAY_NEXT_STAGE,
	ADD_SCORE,//スコア加算
	PLAYER_DEAD,
	LANE_CHANGE_FALL,
	LANE_CHANGE_DOWN_END,
	LANE_CHANGE_END,
	LANE_CHANGE_UP_END,
	USE_SWORD,
	CHANGE_HEAD,
	NECK_SHOOT,
	NECK_BACK_SHOOT,
	NECK_SHOOT_END,
	CHANGE_HEAD_KEY,
	OPERATE_FLAG,
	TUTORIAL_GOAL_FLASH,
	CREATE_METAMOR_EFFECT,//首変更エフェクトの生成を知らせる
	PLAYER_POS_RESET,
};